# This workflow tests the build and run script

name: Script Testing

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      
      - name: Set executable permission
        run: chmod +x gradlew run build tests.sh

      # Runs a single command using the runners shell
      - name: Run tests
        run: ./tests.sh

